#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MysampleDB")]
public partial class MySampleWebDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblOrder(tblOrder instance);
  partial void UpdatetblOrder(tblOrder instance);
  partial void DeletetblOrder(tblOrder instance);
  partial void InserttblProduct(tblProduct instance);
  partial void UpdatetblProduct(tblProduct instance);
  partial void DeletetblProduct(tblProduct instance);
  #endregion
	
	public MySampleWebDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MysampleDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MySampleWebDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MySampleWebDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MySampleWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MySampleWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblOrder> tblOrders
	{
		get
		{
			return this.GetTable<tblOrder>();
		}
	}
	
	public System.Data.Linq.Table<tblProduct> tblProducts
	{
		get
		{
			return this.GetTable<tblProduct>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOrderList")]
	public ISingleResult<GetOrderListResult> GetOrderList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
		return ((ISingleResult<GetOrderListResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetProductList")]
	public ISingleResult<GetProductListResult> GetProductList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProdID", DbType="Int")] System.Nullable<int> prodID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prodID);
		return ((ISingleResult<GetProductListResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOrders")]
public partial class tblOrder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _OrderID;
	
	private System.Nullable<int> _ProdID;
	
	private System.Nullable<int> _Qty;
	
	private System.Nullable<System.DateTime> _OrderDate;
	
	private string _OrderBY;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIDChanging(int value);
    partial void OnOrderIDChanged();
    partial void OnProdIDChanging(System.Nullable<int> value);
    partial void OnProdIDChanged();
    partial void OnQtyChanging(System.Nullable<int> value);
    partial void OnQtyChanged();
    partial void OnOrderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderDateChanged();
    partial void OnOrderBYChanging(string value);
    partial void OnOrderBYChanged();
    #endregion
	
	public tblOrder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdID", DbType="Int")]
	public System.Nullable<int> ProdID
	{
		get
		{
			return this._ProdID;
		}
		set
		{
			if ((this._ProdID != value))
			{
				this.OnProdIDChanging(value);
				this.SendPropertyChanging();
				this._ProdID = value;
				this.SendPropertyChanged("ProdID");
				this.OnProdIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
	public System.Nullable<int> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this.OnQtyChanging(value);
				this.SendPropertyChanging();
				this._Qty = value;
				this.SendPropertyChanged("Qty");
				this.OnQtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> OrderDate
	{
		get
		{
			return this._OrderDate;
		}
		set
		{
			if ((this._OrderDate != value))
			{
				this.OnOrderDateChanging(value);
				this.SendPropertyChanging();
				this._OrderDate = value;
				this.SendPropertyChanged("OrderDate");
				this.OnOrderDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderBY", DbType="NVarChar(50)")]
	public string OrderBY
	{
		get
		{
			return this._OrderBY;
		}
		set
		{
			if ((this._OrderBY != value))
			{
				this.OnOrderBYChanging(value);
				this.SendPropertyChanging();
				this._OrderBY = value;
				this.SendPropertyChanged("OrderBY");
				this.OnOrderBYChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProduct")]
public partial class tblProduct : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProdId;
	
	private string _ProdName;
	
	private System.Nullable<int> _Qty;
	
	private System.Nullable<decimal> _Price;
	
	private string _Description;
	
	private string _InsertBy;
	
	private System.Nullable<System.DateTime> _InsertDateTime;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _UpdateDateTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProdIdChanging(int value);
    partial void OnProdIdChanged();
    partial void OnProdNameChanging(string value);
    partial void OnProdNameChanged();
    partial void OnQtyChanging(System.Nullable<int> value);
    partial void OnQtyChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnInsertByChanging(string value);
    partial void OnInsertByChanged();
    partial void OnInsertDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnInsertDateTimeChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateTimeChanged();
    #endregion
	
	public tblProduct()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ProdId
	{
		get
		{
			return this._ProdId;
		}
		set
		{
			if ((this._ProdId != value))
			{
				this.OnProdIdChanging(value);
				this.SendPropertyChanging();
				this._ProdId = value;
				this.SendPropertyChanged("ProdId");
				this.OnProdIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdName", DbType="NVarChar(50)")]
	public string ProdName
	{
		get
		{
			return this._ProdName;
		}
		set
		{
			if ((this._ProdName != value))
			{
				this.OnProdNameChanging(value);
				this.SendPropertyChanging();
				this._ProdName = value;
				this.SendPropertyChanged("ProdName");
				this.OnProdNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
	public System.Nullable<int> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this.OnQtyChanging(value);
				this.SendPropertyChanging();
				this._Qty = value;
				this.SendPropertyChanged("Qty");
				this.OnQtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertBy", DbType="NVarChar(50)")]
	public string InsertBy
	{
		get
		{
			return this._InsertBy;
		}
		set
		{
			if ((this._InsertBy != value))
			{
				this.OnInsertByChanging(value);
				this.SendPropertyChanging();
				this._InsertBy = value;
				this.SendPropertyChanged("InsertBy");
				this.OnInsertByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> InsertDateTime
	{
		get
		{
			return this._InsertDateTime;
		}
		set
		{
			if ((this._InsertDateTime != value))
			{
				this.OnInsertDateTimeChanging(value);
				this.SendPropertyChanging();
				this._InsertDateTime = value;
				this.SendPropertyChanged("InsertDateTime");
				this.OnInsertDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this.OnUpdateByChanging(value);
				this.SendPropertyChanging();
				this._UpdateBy = value;
				this.SendPropertyChanged("UpdateBy");
				this.OnUpdateByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDateTime
	{
		get
		{
			return this._UpdateDateTime;
		}
		set
		{
			if ((this._UpdateDateTime != value))
			{
				this.OnUpdateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._UpdateDateTime = value;
				this.SendPropertyChanged("UpdateDateTime");
				this.OnUpdateDateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class GetOrderListResult
{
	
	private int _OrderID;
	
	private System.Nullable<int> _ProdID;
	
	private System.Nullable<int> _Qty;
	
	private System.Nullable<System.DateTime> _OrderDate;
	
	private string _OrderBY;
	
	public GetOrderListResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
	public int OrderID
	{
		get
		{
			return this._OrderID;
		}
		set
		{
			if ((this._OrderID != value))
			{
				this._OrderID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdID", DbType="Int")]
	public System.Nullable<int> ProdID
	{
		get
		{
			return this._ProdID;
		}
		set
		{
			if ((this._ProdID != value))
			{
				this._ProdID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
	public System.Nullable<int> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this._Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> OrderDate
	{
		get
		{
			return this._OrderDate;
		}
		set
		{
			if ((this._OrderDate != value))
			{
				this._OrderDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderBY", DbType="NVarChar(50)")]
	public string OrderBY
	{
		get
		{
			return this._OrderBY;
		}
		set
		{
			if ((this._OrderBY != value))
			{
				this._OrderBY = value;
			}
		}
	}
}

public partial class GetProductListResult
{
	
	private int _ProdId;
	
	private string _ProdName;
	
	private System.Nullable<int> _Qty;
	
	private System.Nullable<decimal> _Price;
	
	private string _Description;
	
	private string _InsertBy;
	
	private System.Nullable<System.DateTime> _InsertDateTime;
	
	private string _UpdateBy;
	
	private System.Nullable<System.DateTime> _UpdateDateTime;
	
	public GetProductListResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdId", DbType="Int NOT NULL")]
	public int ProdId
	{
		get
		{
			return this._ProdId;
		}
		set
		{
			if ((this._ProdId != value))
			{
				this._ProdId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdName", DbType="NVarChar(50)")]
	public string ProdName
	{
		get
		{
			return this._ProdName;
		}
		set
		{
			if ((this._ProdName != value))
			{
				this._ProdName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
	public System.Nullable<int> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this._Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this._Price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertBy", DbType="NVarChar(50)")]
	public string InsertBy
	{
		get
		{
			return this._InsertBy;
		}
		set
		{
			if ((this._InsertBy != value))
			{
				this._InsertBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> InsertDateTime
	{
		get
		{
			return this._InsertDateTime;
		}
		set
		{
			if ((this._InsertDateTime != value))
			{
				this._InsertDateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
	public string UpdateBy
	{
		get
		{
			return this._UpdateBy;
		}
		set
		{
			if ((this._UpdateBy != value))
			{
				this._UpdateBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDateTime
	{
		get
		{
			return this._UpdateDateTime;
		}
		set
		{
			if ((this._UpdateDateTime != value))
			{
				this._UpdateDateTime = value;
			}
		}
	}
}
#pragma warning restore 1591
